<?php require("common/doctype-head.php"); ?>
	<?php require("common/nav-and-title.php");
    require("common/logcheck.php");?>

<h2>Database</h2>
<p><img src="images/account.jpg" alt="" />These are settings required for SCMS to connect with your MySQl server. This should have already been taken care of separately by your MySQL database administrator. Since SCMS does not host your data itself, these settings are extremely important so that you can have a place to keep your records.</p>
<p>It is an administrative responsibility to ensure that these settings are correct and safe from prying eyes. For more information, consult your MySQL database administrator.</p>
<br /><p class="calloutwarn">Do not change these settings without asking your database administrator first.</p>
<?php
@include 'lib/config.php';
// If we were asked to make changes, then do so:
if (count($_POST)) {
    // Just update/add the value to the 'data' array
    $dbsettings = array(
            "scmsDbHost" => $_POST["dbhost"],
            "scmsDbUser" => $_POST["dbusername"],
            "scmsDbPassword" => $_POST["dbpassword"]
            );

    // Now save it to disk, create the 'full' file wrapping it in valid PHP
    $file = "<?php \n/*Please do NOT EDIT this file unless you know what you are doing and is authorized to do so!*/\n \n\$dbsettings = " . var_export($dbsettings, true) . ";\n?>\n";
    file_put_contents('lib/config.php', $file, LOCK_EX);
}

echo '<fieldset><legend>MySQL Server Connection Settings</legend>';
$mysqli = new mysqli($dbsettings['scmsDbHost'], $dbsettings['scmsDbUser'], $dbsettings['scmsDbPassword']);

 if (!mysqli_connect_errno()) {
    printf("<p class=\"calloutinfo\">Connected! The following MySQL login info works okay. <br/>Host information: %s\n</p>", mysqli_get_host_info($mysqli));
	mysqli_close($mysqli);
 } else {
    printf("<p class=\"calloutwarn\">Cannot connect to server. Something might be wrong with your MySQL login info or the server is down.</p>");
    }
echo '
<p>Editing these credentials <b>does not</b> affect the corresponding MySQL account itself. It only affects the way SCMS connects to the MySQL server, meaning if these credentials are erroneous, it will seriously affect the performance of SCMS, and could result in data loss or data inaccessibility. In short, hell.</p>
<form action="'.$_SERVER["PHP_SELF"].'" method="POST">
<label for="dbhost">MySQL hostname: </label><input type="text" id="dbhost" name="dbhost" value="'.$dbsettings['scmsDbHost'].'"> This is the MySQL server hosting your SCMS database.<br />
<label for="dbusername">MySQL username: </label><input type="text" id="dbusername" name="dbusername" value="'.$dbsettings['scmsDbUser'].'"></input> This is the MySQL username for SCMS to said server.<br />
<label for="dbpassword">MySQL password: </label><input type="password" id="dbpassword" name="dbpassword" value="'.$dbsettings['scmsDbPassword'].'"> This is the password for the said MySQL username.</input>
<br />
<input type="submit" value="Save changes"/>
</form></fieldset>
';
?>

 <?php include_once("common/footer.php"); ?>