<?php require("common/doctype-head.php"); ?>
	<?php require("common/nav-and-title.php"); ?>
<?php if (isset($_SESSION['valid']) && $_SESSION['valid']) {
   //REDIRECT TO database settings
   header('Location: database.php');
}?>
    <h2>Setting Up Your Database</h2>

    <?php
@include 'lib/config.php';

// If we were asked to make changes, then do so:
if (count($_POST)) {
    // Just update/add the value to the 'data' array
    $dbsettings = array(
            "scmsDbHost" => $_POST["dbhost"],
            "scmsDbUser" => $_POST["dbusername"],
            "scmsDbPassword" => $_POST["dbpassword"]
            );


    // Now save it to disk, create the 'full' file wrapping it in valid PHP
    $file = "<?php \n/*Please do NOT EDIT this file unless you know what you are doing!*/\n \n\$dbsettings = " . var_export($dbsettings, true) . ";\n?>\n";
    file_put_contents('lib/config.php', $file, LOCK_EX);
}

// Echo out the current data diagnostic)
echo "<pre>Current Data is:\n\n";
print_r($dbsettings);
echo "</pre>\n";
//end diagnostic echo

$mysqli = new mysqli($dbsettings['scmsDbHost'], $dbsettings['scmsDbUser'], $dbsettings['scmsDbPassword']);

 if (!mysqli_connect_errno()) {
    printf("<p class=\"calloutinfo\">The following MySQL login info works okay. <br/>Host information: %s\n</p>", mysqli_get_host_info($mysqli));
	mysqli_close($mysqli);
 } else {
    printf("<p class=\"calloutwarn\">Cannot connect to server. Something might be wrong with your MySQL login info.</p>");
    }
echo '
<form action="'.$_SERVER["PHP_SELF"].'" method="POST">
<p><strong>MySQL hostname:</strong><br/>
<input type="text" name="dbhost" value="'.$dbsettings['scmsDbHost'].'"></p>
<p><strong>MySQL username:</strong><br/>
<input type="text" name="dbusername" value="'.$dbsettings['scmsDbUser'].'"></input></p>
<p><strong>MySQL password</strong><br/>
<input type="password" name="dbpassword" value="'.$dbsettings['scmsDbPassword'].'"></input></p>
<p><input type="submit" value="Save"/></p>
</form>
';

// Open the database connection
    if (!($db = mysqli_connect($dbsettings['scmsDbHost'], $dbsettings['scmsDbUser'], $dbsettings['scmsDbPassword']))) {
     // Handle errors
    die('SQL ERROR: Connection failed: Can\'t create the SCMS database. Check your MySQL database server or <a href="common/config.php">access settings</a>.' . mysqli_connect_error());
} else {
//arrays to hold mysql commands to build database.
/////////////////////Create Database and Tables.//////////////////////////////////////////
  //-------------remove this on production------------------------//
if  (mysqli_select_db($db,'scmsDb')){
   exit();
}
else {
}
  //     $mysqlCmd[] = "drop database if exists scmsdb";           //
//--------------------------------------------------------------//


$mysqlCmd[] = "create database scmsDB default character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "use scmsDB";
$mysqlCmd[] = "create table Subjects(subjectCode varchar(25) not null primary key,descTitle varchar(50) not null, units mediumint(20) unsigned not null, withLab bool not null) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table Course(courseID int(10) unsigned not null auto_increment primary key,courseInitials varchar(15) not null, courseName varchar(60) not null, courseDesc varchar(280) null) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table UserType(userTypeID int(10) unsigned not null auto_increment primary key, userTypeDesc varchar(40) not null) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table Department(deptID int(10) unsigned not null auto_increment primary key, deptInitials varchar(20) not null, deptDesc varchar(50) not null) engine = InnoDB character set latin7 collate latin7_general_cs";

$mysqlCmd[] = "create table Curriculum(currID int(20) unsigned primary key not null auto_increment, currYearEffective year(4) not null, semNoEffective int(1) unsigned not null default 1, course int(10) unsigned not null references Course(courseID) on delete no action on update restrict, isReady bool not null default '0', noOfYears int(2) unsigned not null) engine = InnoDB character set latin7 collate latin7_general_cs";

$mysqlCmd[] = "create table Students(
studentID varchar(20) primary key not null,
lastName varchar(40) not null,
firstName varchar(50) not null,
middleName varchar(40) null,
enrolmentClassif enum('regular','irregular','transferee') not null,
scholarship varchar(60) null,
underCurriculum int(10) unsigned null references Curriculum(currID) on delete no action,
course int(10) unsigned not null,
sectionYearLvl int(1) unsigned null,
gender enum('m','f') null,
civilStatus enum('Single','Married','Divorced','Widowed') null,
religion varchar(60) null,
nationality varchar(25) null,
placeOfBirth varchar(80) null,
dOB date null,
address VARCHAR(70) null,
contactNo varchar(40) null,
highSchool varchar(60) null,
highSchoolGPA decimal(5, 2) null,
parentGuardian varchar(70) null,
emergencyContactNo varchar(40) null,
isStillActive bool not null) engine = InnoDB character set latin7 collate latin7_general_cs";

$mysqlCmd[] = "create table StudentsWithSpouse(studentID varchar(20) not null primary key references Students(studentID) on delete no action, spouseName varchar(70) not null,
spouseReligion varchar(60) null, spouseContactNo varchar(40) null) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table Instructors(instructorID int(10) unsigned primary key not null auto_increment, lastName varchar(50) not null, firstName varchar(50) not null, middleName varchar(40) null, employeeID varchar(20) not null,
departmentID int(10) unsigned null references Department(deptID), contractType enum('part-timer','regular') not null ) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table PreRequisites(subjectCode varchar(25) not null, preReqCode varchar(140) not null references Subjects(subjectCode), currID int(20) not null references Curriculum(currID), primary key (subjectCode,currID)) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table InstructorsPerSubject(instructorID int(20) unsigned not null references Instructors(instructorID), subjectCode varchar(25) not null references Subjects(subjectCode), schoolYear year(4) not null, semNo int(2) unsigned not null) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table SubjectByCurr(currID int(10) unsigned not null references Curriculum(currID), subjectCode varchar(25) not null references Subjects(subjectCode), yearLvl int(1) unsigned not null, semNo int(3) unsigned not null, primary key(subjectCode,currID,yearlvl,semno)) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table SubjectsTakenByStudent(studentID varchar(20) not null references Students(studentID), subjectCode varchar(25) not null references Subjects(subjectCode),
schoolYear year(4) not null, semNo int(2) unsigned not null, prelimGrade decimal(3, 2) unsigned, finalGrade decimal(3, 2) unsigned, primary key (studentID,subjectCode,schoolYear,semNo)) engine = InnoDB character set latin7 collate latin7_general_cs";
$mysqlCmd[] = "create table ScmsAdmin(userName varchar(20) not null primary key, password varchar(34) not null, firstName varchar(40) not null, middleName varchar(30) null, lastName varchar(40) not null,
userTypeID int(10) unsigned not null references UserType(userTypeID)) engine = InnoDB character set latin7 collate latin7_general_cs";

//count queries
$s=sizeof($mysqlCmd);
echo "<div id=\"output\">$s queries to execute: starting<br/>";

//load create queries to My SQl server one-by-one
    foreach ($mysqlCmd as $c) {
      if (!$result= mysqli_query($db,$c)){
            //save what error to $err
            $err = mysqli_error($db);
            die("<pre style='background:yellow;'>$c\n</pre><br/>$err<br/><pre style='background:#ddd;'>\nSetup has been rolled back. Please try again from the beginning.</pre>");
       } else {
         echo "<pre style='color:darkgreen;'>$c\n</pre>";
       };
    }
echo "</div>";
//clean the array
unset($mysqlCmd);


/////////////////////Insert records//////////////////////////////////////////

$mysqlCmd[] = "insert into UserType values ('','system administrator'),('','web administrator'),('','database administrator'),('','office staff')";
$mysqlCmd[] = "insert into Department values ('','CCS','College of Computer Studies'), ('','COT','College of Technology'),('','COTED','College of Teacher Education'),('','CAS','College of Arts and Sciences'),('','CEA','College of Engineering and Architecture'),
('','CMED','College of Maritime Education'),('','CBM','College of Business Management'),('','LHS','Laboratory High School')";
$mysqlCmd[] = "insert into ScmsAdmin values ('dev','','Lee Alexis','','Bermejo','1')";

//count queries
$s=sizeof($mysqlCmd);
echo "<div id=\"output\">$s queries to execute: starting<br/>";

//load create queries to My SQl server one-by-one
    foreach ($mysqlCmd as $c) {
      if (!$result= mysqli_query($db,$c)){
            //save what error to $err
            $err = mysqli_error($db);
            die("<pre style='background:yellow;'>$c\n</pre><br/>$err<br/><pre style='background:#ddd;'>\nSetup has been stopped. Please try again from the beginning.</pre>");
       } else {
         echo "<pre style='color:darkgreen;'>$c\n</pre>";
       };
    }
echo "</div>";
//clean the array
unset($mysqlCmd);
//end connection
   mysqli_close($db);
}
?>


<?php include_once("common/footer.php"); ?>

