<?php 
/*Please do NOT EDIT this file unless you know what you are doing!*/
 
$dbsettings = array (
  'scmsDbHost' => 'localhost',
  'scmsDbUser' => 'root',
  'scmsDbPassword' => '',
  'scmsDb' => 'scmsDB',
);
?>
